import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString().split('T')[0];
}

async function main() {
  const deals = [
    {
      dealId: 'D001',
      company: 'Niramai Health',
      founder: 'Dr. Geetha Manjunath',
      sector: 'HealthTech',
      cstage: 'Series A',
      geo: 'India – Bengaluru',
      ask: '₹12 Cr',
      source: 'Inbound – Email',
      owner: 'Priya Mehta',
      url: '',
      summary: 'AI-powered breast cancer screening using thermal imaging.',
      notes: '',
      status: 'IC',
      align: 'High',
      added: daysAgo(18),
      aiFit: 'High',
      aiRisks: 'Regulatory approval timeline; niche market; competition from radiology incumbents',
      aiDate: daysAgo(16),
      callInsights: 'Strong founder background, published research, clear regulatory path',
      callFlags: 'Slow commercialisation',
      callConviction: 'High',
      callDate: daysAgo(14),
      pinGo: 'Go',
      pinNotes: 'Strong thesis fit. Advance to DD.',
      pinDate: daysAgo(12),
      ddrMarket: '₹3,500 Cr addressable by 2027 per ICMR estimates',
      ddrBiz: 'SaaS + device licensing',
      ddrTraction: '8 hospitals, 1,200 scans',
      ddrFounder: 'PhD AI, 15 yrs healthcare',
      ddrRisks: 'Device approval delays',
      ddrDate: daysAgo(6),
      icMemo: 'Strong differentiation, founder credibility, large TAM.',
      icDecision: null,
      icDate: null,
      rejectedReason: null,
      rejectedNotes: null,
      rejectedAt: null,
    },
    {
      dealId: 'D002',
      company: 'Khetify',
      founder: 'Ravi Kumar',
      sector: 'AgriTech',
      cstage: 'Seed',
      geo: 'India – Pune',
      ask: '₹3 Cr',
      source: 'Referral – Founder',
      owner: 'Aditya Nair',
      url: '',
      summary: 'Precision farming SaaS for smallholder farmers using satellite data.',
      notes: 'Interesting IoT angle',
      status: 'Screening',
      align: 'Medium',
      added: daysAgo(9),
      aiFit: 'Medium',
      aiRisks: 'Low ARPU; fragmented farmer base; government competition',
      aiDate: daysAgo(8),
      callInsights: 'Good product clarity, experienced in agri domain',
      callFlags: 'Revenue model unclear',
      callConviction: 'Medium',
      callDate: daysAgo(7),
      pinGo: null,
      pinNotes: null,
      pinDate: null,
      ddrMarket: null,
      ddrBiz: null,
      ddrTraction: null,
      ddrFounder: null,
      ddrRisks: null,
      ddrDate: null,
      icMemo: null,
      icDecision: null,
      icDate: null,
      rejectedReason: null,
      rejectedNotes: null,
      rejectedAt: null,
    },
    {
      dealId: 'D003',
      company: 'EduStack AI',
      founder: 'Samara Iyer',
      sector: 'EdTech',
      cstage: 'Pre-Seed',
      geo: 'India – Delhi',
      ask: '₹1.5 Cr',
      source: 'Inbound – Platform',
      owner: 'Priya Mehta',
      url: '',
      summary: 'Personalised K-12 tutoring via generative AI.',
      notes: '',
      status: 'New Opportunity',
      align: null,
      added: daysAgo(3),
      aiFit: null,
      aiRisks: null,
      aiDate: null,
      callInsights: null,
      callFlags: null,
      callConviction: null,
      callDate: null,
      pinGo: null,
      pinNotes: null,
      pinDate: null,
      ddrMarket: null,
      ddrBiz: null,
      ddrTraction: null,
      ddrFounder: null,
      ddrRisks: null,
      ddrDate: null,
      icMemo: null,
      icDecision: null,
      icDate: null,
      rejectedReason: null,
      rejectedNotes: null,
      rejectedAt: null,
    },
    {
      dealId: 'D004',
      company: 'CarbonLedger',
      founder: 'Ankit Singh',
      sector: 'CleanTech',
      cstage: 'Series A',
      geo: 'India – Mumbai',
      ask: '$1.2M',
      source: 'Outbound – Event',
      owner: 'Ritu Sharma',
      url: '',
      summary: 'Enterprise carbon accounting and offset trading platform.',
      notes: 'Met at ClimateX 2025',
      status: 'Due Diligence',
      align: 'High',
      added: daysAgo(22),
      aiFit: 'High',
      aiRisks: 'Regulatory uncertainty; early market; enterprise sales cycle',
      aiDate: daysAgo(20),
      callInsights: 'Excellent founder, ex-McKinsey, strong network',
      callFlags: 'Enterprise CAC could be high',
      callConviction: 'High',
      callDate: daysAgo(19),
      pinGo: 'Go',
      pinNotes: 'Clear thesis fit. Fast growing space. Move to DD.',
      pinDate: daysAgo(17),
      ddrMarket: '$50B global carbon market by 2030',
      ddrBiz: 'SaaS + transaction fee',
      ddrTraction: '12 enterprise pilots, 3 paying',
      ddrFounder: 'Ex-McKinsey + IIT',
      ddrRisks: 'Policy risk; low switching cost',
      ddrDate: daysAgo(4),
      icMemo: null,
      icDecision: null,
      icDate: null,
      rejectedReason: null,
      rejectedNotes: null,
      rejectedAt: null,
    },
    {
      dealId: 'D005',
      company: 'QuickLend',
      founder: 'Vikram Bose',
      sector: 'FinTech',
      cstage: 'Seed',
      geo: 'India – Chennai',
      ask: '₹4 Cr',
      source: 'Referral – LP',
      owner: 'Aditya Nair',
      url: '',
      summary: 'Embedded BNPL for SME supply chains.',
      notes: '',
      status: 'Rejected',
      align: 'Low',
      added: daysAgo(30),
      aiFit: 'Low',
      aiRisks: 'Regulatory risk; credit quality; competition from banks',
      aiDate: daysAgo(29),
      callInsights: 'Limited founder experience in credit',
      callFlags: 'No clear moat; regulatory grey area',
      callConviction: 'Low',
      callDate: daysAgo(28),
      pinGo: 'No-Go',
      pinNotes: 'Thesis misalignment. Reject.',
      pinDate: daysAgo(27),
      ddrMarket: null,
      ddrBiz: null,
      ddrTraction: null,
      ddrFounder: null,
      ddrRisks: null,
      ddrDate: null,
      icMemo: null,
      icDecision: null,
      icDate: null,
      rejectedReason: 'Thesis / Sector Misalignment',
      rejectedNotes: 'BNPL outside current fund mandate.',
      rejectedAt: 'Screening',
    },
    {
      dealId: 'D006',
      company: 'LogiRoute',
      founder: 'Meera Patel',
      sector: 'Logistics',
      cstage: 'Seed',
      geo: 'India – Ahmedabad',
      ask: '₹6 Cr',
      source: 'Inbound – Email',
      owner: 'Ritu Sharma',
      url: '',
      summary: 'Last-mile delivery optimisation using ML routing.',
      notes: '',
      status: 'Invested',
      align: 'High',
      added: daysAgo(60),
      aiFit: 'High',
      aiRisks: 'Asset-heavy competition; thin margins',
      aiDate: daysAgo(58),
      callInsights: 'Deep domain expertise; strong unit economics demonstrated',
      callFlags: 'Scaling ops may need large capex',
      callConviction: 'High',
      callDate: daysAgo(57),
      pinGo: 'Go',
      pinNotes: 'Strong conviction. Proceed to DD.',
      pinDate: daysAgo(55),
      ddrMarket: '₹10,000 Cr TAM',
      ddrBiz: 'SaaS + revenue share per delivery',
      ddrTraction: '25 enterprise clients, ₹40L MRR',
      ddrFounder: 'Ex-Flipkart Logistics',
      ddrRisks: 'Ops scaling; driver retention',
      ddrDate: daysAgo(45),
      icMemo: 'Outstanding traction; defensible product; strong team. Recommend investment.',
      icDecision: 'Term Sheet',
      icDate: daysAgo(40),
      rejectedReason: null,
      rejectedNotes: null,
      rejectedAt: null,
    },
  ];

  console.log('Seeding database...');

  for (const deal of deals) {
    await prisma.deal.create({
      data: deal,
    });
  }

  console.log('Database seeded with 6 deals');
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
