-- CreateTable
CREATE TABLE "Deal" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "dealId" TEXT NOT NULL,
    "company" TEXT NOT NULL,
    "founder" TEXT NOT NULL,
    "sector" TEXT NOT NULL,
    "cstage" TEXT NOT NULL,
    "geo" TEXT NOT NULL,
    "ask" TEXT NOT NULL,
    "source" TEXT NOT NULL,
    "owner" TEXT NOT NULL,
    "url" TEXT,
    "summary" TEXT NOT NULL,
    "notes" TEXT,
    "status" TEXT NOT NULL DEFAULT 'New Opportunity',
    "align" TEXT,
    "aiFit" TEXT,
    "aiRisks" TEXT,
    "aiDate" TEXT,
    "callInsights" TEXT,
    "callFlags" TEXT,
    "callConviction" TEXT,
    "callDate" TEXT,
    "pinGo" TEXT,
    "pinNotes" TEXT,
    "pinDate" TEXT,
    "ddrMarket" TEXT,
    "ddrBiz" TEXT,
    "ddrTraction" TEXT,
    "ddrFounder" TEXT,
    "ddrRisks" TEXT,
    "ddrDate" TEXT,
    "icMemo" TEXT,
    "icDecision" TEXT,
    "icDate" TEXT,
    "rejectedReason" TEXT,
    "rejectedNotes" TEXT,
    "rejectedAt" TEXT,
    "added" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "Deal_dealId_key" ON "Deal"("dealId");
